services:
  server:
    container_name: server
    build: .
    deploy:
      resources:
        limits:
          memory: 8192M
        reservations:
          memory: 8192M
    ports:
      - 7777:7777/udp
      - 8888:8888/udp
    volumes:
      - server-files:/home
      - ./logs:/server-files/RSDragonwilds/Saved/Logs
      - ./saves:/server-files/RSDragonwilds/Saved/SaveGames
volumes:
  server-files:
    name: server-files